version: '3'

services:
  main:
    build: .
    image: log4j-cve-2021-44228-webserver
    container_name: log4j-cve-2021-44228-webserver
    mem_limit: 300m
    ports:
      - 8080:8080
    cpus: 0.5
    restart: always
